language: go
sudo: false
go:
  - "1.11"
env:
  - GO111MODULE=on
addons:
  apt:
    packages:
      - libpcsclite-dev
os:
  - linux
  - osx

#before_install:
#  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/build/
#  - export TRAVIS_BUILD_DIR=$HOME/build/
#  - cd $HOME/build/

#install:
#  - make get-deps
